---
title: "Many Elastic Net Models for `r params$cancer_type` across layers"
author: "Monti Lab"
date:   "`r format(Sys.Date(), '%B %d, %Y')`"
params: 
  cancer_type: "LAML"
output:
  html_document:
    theme: united
    code_folding: hide
    css: style.css
    toc: true
    toc_float: true
---

```{r opts, echo=FALSE}
#theme: united
## to prevent excessively verbose output
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r render_report, echo=FALSE}
## this is needed only if you want to generate different versions of the output html
#render_report <- function(
#    rmd = rstudioapi::getSourceEditorContext()$path, # the current source file
#    cancer_type ) {
  #cancer_type <- match.arg(cancer_type)
#  rmarkdown::render(
#    rmd,
#    params = list(cancer_type = cancer_type),
#    output_file = paste(tools::file_path_sans_ext(rmd), cancer_type, "html", sep = ".")
#  )
#}
# E.g.,
#
#render_report(cancer_type = "HNSC") 
#   --> "/path/<rmarkdown_stub>.hnsc.html"
# render_report(cancer_type = "brca") 
#   --> "/path/<rmarkdown_stub>.brca.html"
```

```{r cancer type load, include=FALSE}
library(knitr)
library(glue)
library(reactable)

cancer_type <- params$cancer_type
library(htmltools) 
library(e1071) 
library(caTools) 
library(class)
#library(TimeSeriesExperiment)
#library(SummarizedExperiment)
#library(Biobase)
#library(ggplot2)
#library(caret)
# source("InitialSteps.Rmd")
knitr::knit("ModelBuilding.Rmd", output = tempfile())
knitr::knit("Analysis.Rmd", output = tempfile())
source("PanClockHelperFunctions.R")
setwd("/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/scripts/GitCore/scripts")

```

# Get the output of the ML model (loop through all layer combinations)
```{r Setting Model Combinations}
# Personalized Layer Combinations

#layer_combinations <- list(c("miRNA"),c("RPPA"))
#layer_combinations <- list(c("miRNA"))
#layer_combinations <- list(c("miRNA"),c("miRNA","RPPA"))
#layer_combinations <- list(c("miRNA"),c("RPPA"),c("RNASeq"),c("miRNA","RPPA"),c("miRNA","RNASeq"),c("RNASeq","RPPA"), c("miRNA","RPPA","RNAseq")) #w/o methylation
#layer_combinations <- list(c("miRNA"),c("RPPA"))

#layer_combinations <- list(c("methylation"),c("miRNA"),c("RPPA"),c("RNAseq"),c("miRNA","RPPA"),c("miRNA","RNAseq"),c("RNAseq","RPPA"), c("miRNA","RPPA","RNAseq"))

#layer_combinations <- list(c("miRNA"), c("RNAseq"), c("methylation"), c("miRNA","RNAseq"), c("miRNA","methylation"))

#layer_combinations <- list(c("methylation"))
#The correct form of writing it is RNAseq, case sensitive

#Given a series of models, perform all possible combinations

#testing w/o RNAseq RPPA miRNA


models <- c("miRNA","RPPA","RNAseq", "methylation")
layer_combinations <- unlist(lapply(1:length(models), function(x) {
  combn(models, x, simplify = FALSE)
}), recursive = FALSE)

for (comb in layer_combinations){
  print(comb)
}
```
# Running Elastic Net Models for: {.tabset}
```{r, Running Models, results = 'asis'}
#Initcializing a coefficient empty list so to append after every run
coef_list <- list()

# reactable_pretty <- function(results) {
#   results <- results %>% 
#     mutate(across(where(~is.numeric(.) && any(. %% 1 != 0, na.rm = TRUE)), 
#                   ~signif(., digits = 3))) 
#   
#   reactable::reactable(results, searchable = TRUE, resizable = TRUE)
# }


cancer_summary_table <- data.frame(
  test_name = character(),
  cancer_type = character(),
  layer_combination = character(),
  
  Rsquared = numeric(),
  RMSE = numeric(),
  
  delta_age_coeff_non_interaction	= numeric(),
  delta_age_exp_coeff_non_interaction = numeric(),
  delta_age_pval_non_interaction = numeric(),
  chronological_coef_non_interaction = numeric(),
  chronological_exp_coef_non_interaction = numeric(),
  chronological_pval_non_interaction = numeric(),

  Concordance_non_interaction = numeric(),
  se_concordance_non_interaction = numeric(),
  lik_ratio_test_non_interaction = numeric(),
  lik_ratio_test_df_non_interaction = numeric(),
  lik_ratio_test_pval_non_interaction = numeric(),
  Wald_test_non_interaction = numeric(),
  Wald_test_df_non_interaction = numeric(),
  Wald_test_pval_non_interaction = numeric(),
  logrank_score_test_non_interaction = numeric(),
  logrank_score_test_df_non_interaction = numeric(),
  logrank_score_test_pval_non_interaction = numeric(),
  
  delta_age_coeff_interaction	= numeric(),
  delta_age_exp_coeff_interaction = numeric(),
  delta_age_pval_interaction = numeric(),
  chronological_coef_interaction = numeric(),
  chronological_exp_coef_interaction = numeric(),
  chronological_pval_interaction = numeric(),

  Concordance_interaction = numeric(),
  se_concordance_interaction = numeric(),
  lik_ratio_test_interaction = numeric(),
  lik_ratio_test_df_interaction = numeric(),
  lik_ratio_test_pval_interaction = numeric(),
  Wald_test_interaction = numeric(),
  Wald_test_df_interaction = numeric(),
  Wald_test_pval_interaction = numeric(),
  logrank_score_test_interaction = numeric(),
  logrank_score_test_df_interaction = numeric(),
  logrank_score_test_pval_interaction = numeric(),
  
  delta_age_coeff_baseline	= numeric(),
  delta_age_exp_coeff_baseline = numeric(),
  delta_age_pval_baseline = numeric(),
  chronological_coef_baseline = numeric(),
  chronological_exp_coef_baseline = numeric(),
  chronological_pval_baseline = numeric(),

  Concordance_baseline = numeric(),
  se_concordance_baseline = numeric(),
  lik_ratio_test_baseline = numeric(),
  lik_ratio_test_df_baseline = numeric(),
  lik_ratio_test_pval_baseline = numeric(),
  Wald_test_baseline = numeric(),
  Wald_test_df_baseline = numeric(),
  Wald_test_pval_baseline = numeric(),
  logrank_score_test_baseline = numeric(),
  logrank_score_test_df_baseline = numeric(),
  logrank_score_test_pval_baseline = numeric()
  )


# Iterate through all values in layer_combinations
for (comb in layer_combinations) {
  # Generate tab heading based on the combination
  #cat(paste("Elastic Net model for", comb, "\n\n"))
  #combination <- comb
  cat("\n\n##", comb, "\n\n")

  # Run standardized model building
  existingExperimentList <- NULL
  modelOutput <- standardizedModelBuilding(comb,
                                           cancerName = cancer_type,
                                           methodNames = c("glmnet"),
                                           splitSize = 0.99,
                                           seed = 43)

  # Extract lambda values and coefficients
  lambda_values <- modelOutput$ModelBuilding$model$finalModel$lambda
  closest_lambda_index <- which.min(abs(lambda_values - modelOutput$ModelBuilding$model$finalModel$lambdaOpt))
  beta_matrix <- modelOutput$ModelBuilding$model$finalModel$beta
  coef_names <- rownames(beta_matrix)
  beta_column <- beta_matrix[, closest_lambda_index]

  coef_df <- data.frame(
    Feature = coef_names,
    Weight = as.numeric(beta_column)
  )
  rownames(coef_df) <- coef_df$Feature

  # Separate non-zero and zero coefficients
  non_zero_coef_df <- coef_df[coef_df$Weight != 0, ]
  zero_coef_df <- coef_df[coef_df$Weight == 0, ]

  # Print summary statistics for non-zero coefficients
  cat(paste("\n\n There are", nrow(non_zero_coef_df), "features with non-zero weights in this model.\n\n"))
  cat(paste("There are", nrow(zero_coef_df), "features with zero weight in this model.\n\n"))
  # Ensure `comb` is always converted into a single string
  coef_list[[paste0(cancer_type, "_", paste(comb, collapse = "_"))]] <- coef_df


  # Calculate and display survival statistics
  cat("\n\n### Evaluating delta age on Survival(coxph)\n\n")
  stats <- getSurvivalStats(modelOutput$experimentList[[1]],
                            modelOutput$ModelBuilding$predicted)
  
  cat("\n\n#### Non Interaction Coxph Model\n\n")
  cox_summary_ni <- capture.output(stats$non_interaction_summary)
  cat("```\n", paste(cox_summary_ni, collapse = "\n"), "\n```\n")
  
  cat("\n\n#### Interaction Coxph Model\n\n")
  cox_summary_i <- capture.output(stats$interaction_summary)
  cat("```\n", paste(cox_summary_i, collapse = "\n"), "\n```\n")
  
  cat("\n\n#### Baseline Coxph Model\n\n")
  cox_summary_b <- capture.output(stats$baseline_summary)
  cat("```\n", paste(cox_summary_b, collapse = "\n"), "\n```\n")
  
  #Making summary tables df1 <- (model performance & coxph) & df2 <- (coefficients and model weight)
  cancer_summary_table <- rbind(cancer_summary_table,
                                data.frame(
                                  test_name = "elastic_net",
                                  cancer_type = cancer_type,
                                  layer_combination = paste(comb, collapse = "_"),
                                  Rsquared = modelOutput$ModelBuilding$model$R2,
                                  RMSE = modelOutput$ModelBuilding$model$RMSE,
                                  
                                  delta_age_coeff_non_interaction	= stats$non_interaction_summary$coefficients["delta_age", "coef"],
                                  delta_age_exp_coeff_non_interaction = stats$non_interaction_summary$coefficients["delta_age", "exp(coef)"],
                                  delta_age_pval_non_interaction = stats$non_interaction_summary$coefficients["delta_age", "Pr(>|z|)"],
                                  chronological_coef_non_interaction = stats$non_interaction_summary$coefficients["chronological", "coef"],
                                  chronological_exp_coef_non_interaction = stats$non_interaction_summary$coefficients["chronological", "exp(coef)"],
                                  chronological_pval_non_interaction =  stats$non_interaction_summary$coefficients["chronological", "Pr(>|z|)"],
                                  
                                  Concordance_non_interaction = stats$non_interaction_summary$concordance[1],
                                  se_concordance_non_interaction = stats$non_interaction_summary$concordance[2],
                                  lik_ratio_test_non_interaction = stats$non_interaction_summary$logtest["test"],
                                  lik_ratio_test_df_non_interaction = stats$non_interaction_summary$logtest["df"],
                                  lik_ratio_test_pval_non_interaction = stats$non_interaction_summary$logtest["pvalue"],
                                  Wald_test_non_interaction = stats$non_interaction_summary$waldtest["test"],
                                  Wald_test_df_non_interaction = stats$non_interaction_summary$waldtest["df"],
                                  Wald_test_pval_non_interaction = stats$non_interaction_summary$waldtest["pvalue"],
                                  logrank_score_test_non_interaction = stats$non_interaction_summary$sctest["test"],
                                  logrank_score_test_df_non_interaction = stats$non_interaction_summary$sctest["df"],
                                  logrank_score_test_pval_non_interaction = stats$non_interaction_summary$sctest["pvalue"],
                                  
                                  delta_age_coeff_interaction = stats$interaction_summary$coefficients["delta_age", "coef"],
delta_age_exp_coeff_interaction = stats$interaction_summary$coefficients["delta_age", "exp(coef)"],
delta_age_pval_interaction = stats$interaction_summary$coefficients["delta_age", "Pr(>|z|)"],
chronological_coef_interaction = stats$interaction_summary$coefficients["chronological", "coef"],
chronological_exp_coef_interaction = stats$interaction_summary$coefficients["chronological", "exp(coef)"],
chronological_pval_interaction = stats$interaction_summary$coefficients["chronological", "Pr(>|z|)"],

Concordance_interaction = stats$interaction_summary$concordance[1],
se_concordance_interaction = stats$interaction_summary$concordance[2],
lik_ratio_test_interaction = stats$interaction_summary$logtest["test"],
lik_ratio_test_df_interaction = stats$interaction_summary$logtest["df"],
lik_ratio_test_pval_interaction = stats$interaction_summary$logtest["pvalue"],
Wald_test_interaction = stats$interaction_summary$waldtest["test"],
Wald_test_df_interaction = stats$interaction_summary$waldtest["df"],
Wald_test_pval_interaction = stats$interaction_summary$waldtest["pvalue"],
logrank_score_test_interaction = stats$interaction_summary$sctest["test"],
logrank_score_test_df_interaction = stats$interaction_summary$sctest["df"],
logrank_score_test_pval_interaction = stats$interaction_summary$sctest["pvalue"],

chronological_coef_baseline = stats$baseline_summary$coefficients["chronological", "coef"],
chronological_exp_coef_baseline = stats$baseline_summary$coefficients["chronological", "exp(coef)"],
chronological_pval_baseline = stats$baseline_summary$coefficients["chronological", "Pr(>|z|)"],

Concordance_baseline = stats$baseline_summary$concordance[1],
se_concordance_baseline = stats$baseline_summary$concordance[2],
lik_ratio_test_baseline = stats$baseline_summary$logtest["test"],
lik_ratio_test_df_baseline = stats$baseline_summary$logtest["df"],
lik_ratio_test_pval_baseline = stats$baseline_summary$logtest["pvalue"],
Wald_test_baseline = stats$baseline_summary$waldtest["test"],
Wald_test_df_baseline = stats$baseline_summary$waldtest["df"],
Wald_test_pval_baseline = stats$baseline_summary$waldtest["pvalue"],
logrank_score_test_baseline = stats$baseline_summary$sctest["test"],
logrank_score_test_df_baseline = stats$baseline_summary$sctest["df"],
logrank_score_test_pval_baseline = stats$baseline_summary$sctest["pvalue"]
                                ))
}
#modelOutput$ModelBuilding$model$bestTune

#	alpha = 0.325 , lambda = 2.622266	
#R2 = 0.07792129 , RMSE = 12.09510

#Actually Printed:
#R^2: 0.450447682230494 - RMSE: 10.1432852941834 (miRNA, RPPA)
#R^2: 0.302809578447203 - RMSE: 10.7884802061178 (miRNA)

```
## Model Weights
```{r Printing Model Weights, results='asis'}
#names(coef_list)

#searchable = true

cat("\n\n# Model Weights\n\n")

# Create a list of HTML tags, each containing a header + reactable
# all_tables <- lapply(names(coef_list), function(placeholder) {
#   div(
#     h3(placeholder),
#     reactable(coef_list[[placeholder]], searchable = TRUE)
#   )
# })
#taglist(all_tables)


all_tables <- lapply(names(coef_list), function(placeholder) {
  div(
    h3(placeholder),
    reactable(
      coef_list[[placeholder]] %>% 
        mutate(across(where(~is.numeric(.) && any(. %% 1 != 0, na.rm = TRUE)), 
                      ~signif(., digits = 3))),
      searchable = TRUE
    )
  )
})

tagList(all_tables)
```

```{r making result files, echo=FALSE}
#Making the datatable csv's and rds

######### For model weights: #########
file_path <- paste0("/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/scripts/GitCore/results/", cancer_type, "_elastic_net_omics_combinations_model_weights.rds")

saveRDS(coef_list, file = file_path)



######### For summary table #########
file_path <- paste0("/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/scripts/GitCore/results/", 
                    cancer_type, 
                    "_elastic_net_omics_combinations.csv")

write.csv(cancer_summary_table, file_path, row.names = FALSE)

```

## Session Info
```{r session info}
sessionInfo()
```