---
title: "PanEverythingSurvivalClock"
output: html_notebook
---

```{r, Load, message=FALSE, warning=FALSE, include=FALSE}
library(e1071) 
library(SummarizedExperiment)
library(Biobase)
library(ggplot2)
library(caret)
library(dplyr)
library(survival)
library(reactable)
library(survminer)
library(vip)
library(tidyverse)
setwd("/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/scripts/Eitan/Pancancer_Aging_Clocks/scripts")

# Comment in if running from shell script
# system("Rscript -e 'knitr::purl(\"ModelBuilding.Rmd\", output = \"ModelBuilding.R\")'")
# source("ModelBuilding.R")
# system("Rscript -e 'knitr::purl(\"Analysis.Rmd\", output = \"Analysis.R\")'")
# source("Analysis.R")

# Comment in if running here
knitr::knit("Analysis.Rmd", output = tempfile())
knitr::knit("ModelBuilding.Rmd", output = "ModelBuilding.R")
knitr::knit("pathways_enrichment/pathways_enrichment.Rmd", output = "pathways_enrichment/pathways_enrichment.R")
source("PanClockHelperFunctions.R")
library(doParallel)
registerDoParallel(cores = 4)  # Reduce parallel threads
```

# Get the output of the ML model
```{r, Model}
Sys.setenv(R_MAX_STACK_SIZE = "50000000000")  # Increase to 50000MB
options(expressions = 500000)

# existingExperimentList <- getNormalSize("KIRC")
existingExperimentList <- NULL
# expRNAseq <- getExperimentByLayerAndCancer("RNAseq", "BRCA")
# expRNAseqNormal <- getExperimentByLayerAndCancer("RNAseq_Normal", "BRCA")
# reducedRNAseq <- reduceExperimentBySubjects(expRNAseq[[1]], expRNAseqNormal[[1]])
# reducedRNAseqNormal <- reduceExperimentBySubjects(expRNAseqNormal[[1]], reducedRNAseq)

cancerType <- "UCEC"
layers <- c("RNAseq")
iterationCount <- 1
modelOutput <- standardizedModelBuilding(layers, cancerName=cancerType, methodNames=c("ElasticNet"), splitSize=1, seed=43, existingExperimentsList=existingExperimentList, iterationCount=iterationCount, applyBiasCorrection=TRUE, combiningNormal=FALSE, scaleByNormal=FALSE, significanceCutoff=0.05, predictor="age", featuresToEncode=c("gender", "subtype_selected"))
existingExperimentList <- modelOutput$experimentList
```

# Survival analysis given model just ran
```{r, Survival}
### Collect survival analysis data
stats <- getSurvivalStats(modelOutput$experimentList[[1]], modelOutput$ModelBuilding$predicted, applyBiasCorrection=FALSE, useCovariates=FALSE, degreesFreedomNonLinear=8, useComplicatedNonlinear=FALSE)
# anno <- getGeneMap(modelOutput)
# survDF <- stats$survDF
# DEtable <- differentialExpression(modelOutput$experimentList, survDF, anno, label="normal")
# write.table(DEtable, file = "DE_Table_TumorvsNormal.csv") 

# survivalStats <- survivalOnlyFeatures(modelOutput)
# summary(survivalStats)
statsTable <- getFormattedStatsTable(stats)
summaryTable <- initializeSummaryTable()
summaryTable <- rbind(summaryTable, getSummaryTable(layers, modelOutput, stats))


# Test: Age + delta_age
print(stats$non_interaction_linear_summary) # Linear age + delta age
print(stats$non_interaction_nonlinear_summary) # Nonlinear age + delta_age
print(stats$baseline_nonlinear_summary) # Nonlinear age
print(stats$baseline_summary) # Linear age

# Test: Age * delta_age (Passes BRCA RNAseq no bias, fails BRCA RNAseq bias)
print(stats$interaction_linear_summary) # Linear age * delta age
print(stats$baseline_interaction_summary) # Linear age * linear age

# Test: Age * age + Age * delta_age (Passes BRCA RNAseq no bias, narrowly passes BRCA RNAseq bias)
print(stats$interaction_linear_duplicate_summary) # Linear age * linear age + linear age * delta age
print(stats$baseline_interaction2_summary) # Linear age * linear age + linear age * linear age

# Test: Nonlinear age + age * delta_age (Passes BRCA RNAseq no bias, narrowly passes BRCA RNAseq bias)
print(stats$interaction_additive_nonlinear_summary) # Nonlinear age + linear age * delta_age
print(stats$baseline_interaction_nonlinear_additive_summary) # Nonlinear age + linear age * linear age

# Test: Nonlinear age * delta_age (Fails BRCA RNAseq no bias, passes BRCA RNAseq bias, passes UCEC RNAseq bias)
print(stats$interaction_multiplicative_nonlinear_summary) # Nonlinear age * delta_age
print(stats$baseline_interaction_nonlinear_multiplicative_summary) # Nonlinear age * age

# Test: Nonlinear Age * Age + nonlinear age * delta_age (Passes BRCA RNAseq no bias, passes BRCA RNAseq bias, passes UCEC RNAseq bias)
print(stats$interaction_nonlinear_duplicate_summary) # Nonlinear Age * Age + nonlinear age * delta_age
print(stats$baseline_interaction_nonlinear_multiplicative2_summary) # Nonlinear age * age + nonlinear age * age


# plotHazardRatio(stats$non_interaction_model, modelOutput$ModelBuilding$predicted$Age, "Non-Interaction Hazard Ratio of Delta Age", x="chronological", y="delta_age", usingInteractionTerm=FALSE)

# plotHazardRatio(stats$interaction_model, scale(modelOutput$ModelBuilding$predicted$Age), "Interaction Hazard Ratio of Delta Age", x="chronological", y="delta_age", usingInteractionTerm=TRUE, scale=1)
# plotHazardRatiosMultiDelta(stats$interaction_model, getZScores(modelOutput$ModelBuilding$predicted$Age), delta_age_values = c(-1, 0, 1))
title <- paste(cancerType, layers[1], "Bias Corrected")
plotHazardRatiosMultiDelta(stats$interaction_multiplicative_nonlinear_model, stats$survDF, delta_age_values = c(2.5, 2, 3), title=title)
proportionalityAssumptionTest <- cox.zph(stats$interaction_linear_model)
# vif(stats$non_interaction_model)

```


```{r, SurvivalPlotting}
# Extract baseline hazard function
stats <- getSurvivalStats(modelOutput$experimentList[[1]], modelOutput$ModelBuilding$predicted, applyBiasCorrection=FALSE, useCovariates=TRUE)
survDF <- stats$survDF
base_haz <- basehaz(stats$non, centered = FALSE)
survDF$hazard <- approx(base_haz$time, base_haz$hazard, xout = survDF$surv[, 1], rule = 2)$y
columnNames <- c("chronological", "delta_age", "gender.y", "surv")
newdata <- data.frame(chronological=survDF$chronological, delta_age=survDF$delta_age, gender.y=survDF$gender.y, surv=survDF$surv, submitter_id=survDF$submitter_id)

chronological_df <- with(survDF,
               data.frame(gender.y = c("female", "female", "female"),
                          chronological = c(-1, 0, 1)
                          )
               )
fit <- survfit(stats$baseline_model, data = survDF, newdata = chronological_df)
ggsurvplot(fit, conf.int = TRUE, legend.labs=c("30", "60", "90"),
           ggtheme = theme_minimal())

base_haz <- basehaz(stats$biological_model, centered = FALSE)
survDF$hazard <- approx(base_haz$time, base_haz$hazard, xout = survDF$surv[, 1], rule = 2)$y
biological_age_df <- with(survDF,
               data.frame(gender.y = c("female", "female", "female"), 
                          predicted = c(30, 60, 90)
                          )
               )
fit <- survfit(stats$biological_model, data = survDF, newdata = biological_age_df)
ggsurvplot(fit, conf.int = TRUE, legend.labs=c("30", "60", "90"),
           ggtheme = theme_minimal(), xlab="Years after sample collection")


base_haz <- basehaz(stats$non_interaction_model, centered = FALSE)
survDF$hazard <- approx(base_haz$time, base_haz$hazard, xout = survDF$surv[, 1], rule = 2)$y
delta_age_df <- with(survDF,
               data.frame(gender.y = c("female", "female"), 
                          chronological = rep(mean(chronological, na.rm = TRUE), 2),
                          delta_age = c(0, 3)
                          )
               )
fit <- survfit(stats$non_interaction_model, data = survDF, newdata = delta_age_df)
ggsurvplot(fit, conf.int = TRUE, legend.labs=c("Delta = 0", "Delta = 3"),
           ggtheme = theme_minimal(), xlab="Years after sample collection")
```

### Save outputs of survival and age model
```{r, SaveClock}
dir = "/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/results/NoFiltering/"
additionalDescriptor <- "Ridge"
clockOutput <- saveClockOutput(cancerType, layers, modelOutput, dir, additionalDescriptor, crossValidating=(iterationCount > 1))
```

# ### Feature analysis given model just run
# ```{r}
# performEnrichment(cancerType, layers, additionalDescriptor, clockOutput)
# ```

# Survival analysis given previous data
```{r}
# results <- read.csv("/restricted/projectnb/agedisease/projects/pancancer_aging_clocks/results/ElasticNet_HNSC_HPV_Negative/ElasticNetRNAseqCompleteSet.csv")
# experiment <- getExperimentByLayerAndCancer("miRNA", "HNSC")
# stats <- getSurvivalStats(experiment[[1]], results)
# summary(stats$interaction_model)
```
